language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    
before_install:
  - chmod +x gradlew

script: ./gradlew check